# Generated by Django 4.1.1 on 2022-09-08 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cesmericanas', '0002_funcionario_ofertas_pagamento_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertas',
            name='Produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cesmericanas.produto'),
        ),
    ]
